select * from customer limit 20
--1. Total Revenue generated by Male vs. Female?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2. Used discount but still spent more than average?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' 
and purchase_amount>=(select AVG(purchase_amount) from customer)

--3. Top 5 products with highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. Compare the average Purchase Amount between Std and Express Shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5. Revenue contribution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;